"""create_encuentros_y_guardias

Revision ID: 2f900dcbe886
Revises: bc500c50d1fd
Create Date: 2026-06-06 18:18:44.216977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f900dcbe886'
down_revision: Union[str, Sequence[str], None] = 'bc500c50d1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_encuentro',
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('dia_semana', sa.Enum('LUNES', 'MARTES', 'MIERCOLES', 'JUEVES', 'VIERNES', 'SABADO', 'DOMINGO', name='diasemanaenum'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('cant_semanas', sa.Integer(), nullable=False),
    sa.Column('meet_url', sa.String(length=500), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guardia',
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('asignacion_id', sa.UUID(), nullable=False),
    sa.Column('dia_semana', sa.String(length=100), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'APROBADA', 'CANCELADA', name='estadoguardiaenum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instancia_encuentro',
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.Enum('PROGRAMADO', 'REALIZADO', 'SUSPENDIDO', name='estadoencuentroenum'), nullable=False),
    sa.Column('meet_url', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['slot_encuentro.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('asignacion', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_asignacion_tenant_deleted_at'), table_name='asignacion')
    op.drop_index(op.f('idx_asignacion_usuario_vigencia'), table_name='asignacion')
    op.drop_index(op.f('idx_audit_log_accion'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_actor'), table_name='audit_log')
    op.drop_index(op.f('idx_audit_log_tenant'), table_name='audit_log')
    op.create_index(op.f('ix_comunicacion_destinatario_hash'), 'comunicacion', ['destinatario_hash'], unique=False)
    op.drop_index(op.f('idx_permiso_tenant_deleted_at'), table_name='permiso')
    op.drop_constraint(op.f('uq_permiso_tenant_nombre'), 'permiso', type_='unique')
    op.drop_index(op.f('idx_rol_tenant_deleted_at'), table_name='rol')
    op.drop_constraint(op.f('uq_rol_tenant_nombre'), 'rol', type_='unique')
    op.alter_column('rol_permiso', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_rol_permiso_tenant_deleted_at'), table_name='rol_permiso')
    op.drop_constraint(op.f('uq_rol_permiso_unique'), 'rol_permiso', type_='unique')
    op.drop_index(op.f('idx_token_refresco_deleted_at'), table_name='token_refresco')
    op.drop_constraint(op.f('token_refresco_token_key'), 'token_refresco', type_='unique')
    op.create_index(op.f('ix_token_refresco_familia_id'), 'token_refresco', ['familia_id'], unique=False)
    op.create_index(op.f('ix_token_refresco_token'), 'token_refresco', ['token'], unique=True)
    op.drop_index(op.f('idx_usuario_deleted_at'), table_name='usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_usuario_deleted_at'), 'usuario', ['deleted_at'], unique=False)
    op.drop_index(op.f('ix_token_refresco_token'), table_name='token_refresco')
    op.drop_index(op.f('ix_token_refresco_familia_id'), table_name='token_refresco')
    op.create_unique_constraint(op.f('token_refresco_token_key'), 'token_refresco', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_token_refresco_deleted_at'), 'token_refresco', ['deleted_at'], unique=False)
    op.create_unique_constraint(op.f('uq_rol_permiso_unique'), 'rol_permiso', ['tenant_id', 'rol_id', 'permiso_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_rol_permiso_tenant_deleted_at'), 'rol_permiso', ['tenant_id', 'deleted_at'], unique=False)
    op.alter_column('rol_permiso', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_rol_tenant_nombre'), 'rol', ['tenant_id', 'nombre'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_rol_tenant_deleted_at'), 'rol', ['tenant_id', 'deleted_at'], unique=False)
    op.create_unique_constraint(op.f('uq_permiso_tenant_nombre'), 'permiso', ['tenant_id', 'nombre'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_permiso_tenant_deleted_at'), 'permiso', ['tenant_id', 'deleted_at'], unique=False)
    op.drop_index(op.f('ix_comunicacion_destinatario_hash'), table_name='comunicacion')
    op.create_index(op.f('idx_audit_log_tenant'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_audit_log_actor'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('idx_audit_log_accion'), 'audit_log', ['accion'], unique=False)
    op.create_index(op.f('idx_asignacion_usuario_vigencia'), 'asignacion', ['usuario_id', 'desde', 'hasta'], unique=False)
    op.create_index(op.f('idx_asignacion_tenant_deleted_at'), 'asignacion', ['tenant_id', 'deleted_at'], unique=False)
    op.alter_column('asignacion', 'tenant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('instancia_encuentro')
    op.drop_table('guardia')
    op.drop_table('slot_encuentro')
    # ### end Alembic commands ###
