"""create_calificacion_and_umbral

Revision ID: fbbfb2cc45f9
Revises: 0c396488b5e9
Create Date: 2026-06-03 18:31:04.667527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbfb2cc45f9'
down_revision: Union[str, Sequence[str], None] = '0c396488b5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umbral_materia',
    sa.Column('asignacion_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('umbral_pct', sa.Integer(), nullable=False),
    sa.Column('valores_aprobatorios', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignacion_id'], ['asignacion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'asignacion_id', 'materia_id', name='uix_umbral_tenant_asignacion_materia')
    )
    op.create_index('idx_umbral_lookup', 'umbral_materia', ['tenant_id', 'asignacion_id', 'materia_id'], unique=False)
    op.create_table('calificacion',
    sa.Column('entrada_padron_id', sa.UUID(), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('actividad', sa.String(length=255), nullable=False),
    sa.Column('nota_numerica', sa.Float(), nullable=True),
    sa.Column('nota_textual', sa.String(length=100), nullable=True),
    sa.Column('aprobado', sa.Boolean(), nullable=False),
    sa.Column('finalizado', sa.Boolean(), nullable=False),
    sa.Column('es_numerica', sa.Boolean(), nullable=False),
    sa.Column('origen', sa.String(length=50), nullable=False),
    sa.Column('importado_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entrada_padron_id'], ['entrada_padron.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calificacion_docente', 'calificacion', ['tenant_id', 'docente_id', 'materia_id'], unique=False)
    op.create_index('idx_calificacion_lookup', 'calificacion', ['tenant_id', 'entrada_padron_id', 'materia_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_calificacion_lookup', table_name='calificacion')
    op.drop_index('idx_calificacion_docente', table_name='calificacion')
    op.drop_table('calificacion')
    op.drop_index('idx_umbral_lookup', table_name='umbral_materia')
    op.drop_table('umbral_materia')
    # ### end Alembic commands ###
