"""estructura_academica

Revision ID: 6f2bdeffd594
Revises: 004_audit_log
Create Date: 2026-06-02 23:16:42.056410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f2bdeffd594'
down_revision: Union[str, Sequence[str], None] = '004_audit_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('codigo', sa.String(length=100), nullable=False),
        sa.Column('nombre', sa.String(length=255), nullable=False),
        sa.Column('estado', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'codigo', name='uix_carrera_tenant_codigo')
    )
    op.create_index('idx_carrera_tenant_codigo', 'carreras', ['tenant_id', 'codigo'], unique=False)
    op.create_index(op.f('ix_carreras_codigo'), 'carreras', ['codigo'], unique=False)

    op.create_table('materias',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('codigo', sa.String(length=100), nullable=False),
        sa.Column('nombre', sa.String(length=255), nullable=False),
        sa.Column('estado', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'codigo', name='uix_materia_tenant_codigo')
    )
    op.create_index('idx_materia_tenant_codigo', 'materias', ['tenant_id', 'codigo'], unique=False)
    op.create_index(op.f('ix_materias_codigo'), 'materias', ['codigo'], unique=False)

    op.create_table('cohortes',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('tenant_id', sa.UUID(), nullable=True),
        sa.Column('carrera_id', sa.UUID(), nullable=False),
        sa.Column('nombre', sa.String(length=255), nullable=False),
        sa.Column('anio', sa.Integer(), nullable=False),
        sa.Column('vig_desde', sa.Date(), nullable=False),
        sa.Column('vig_hasta', sa.Date(), nullable=True),
        sa.Column('estado', sa.String(length=50), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'carrera_id', 'nombre', name='uix_cohorte_tenant_carrera_nombre')
    )
    op.create_index('idx_cohorte_tenant_carrera_nombre', 'cohortes', ['tenant_id', 'carrera_id', 'nombre'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cohorte_tenant_carrera_nombre', table_name='cohortes')
    op.drop_table('cohortes')
    op.drop_index(op.f('ix_materias_codigo'), table_name='materias')
    op.drop_index('idx_materia_tenant_codigo', table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_carreras_codigo'), table_name='carreras')
    op.drop_index('idx_carrera_tenant_codigo', table_name='carreras')
    op.drop_table('carreras')
    # ### end Alembic commands ###
