"""create_padron_tables

Revision ID: 0c396488b5e9
Revises: dc0121369dca
Create Date: 2026-06-03 16:34:34.163846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c396488b5e9'
down_revision: Union[str, Sequence[str], None] = 'dc0121369dca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from app.core.types import EncryptedString
    op.create_table('version_padron',
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('cohorte_id', sa.UUID(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohortes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_padron_lookup', 'version_padron', ['tenant_id', 'materia_id', 'cohorte_id'], unique=False)
    op.create_index('uix_version_padron_active', 'version_padron', ['tenant_id', 'materia_id', 'cohorte_id'], unique=True, postgresql_where=sa.text('activa = true AND deleted_at IS NULL'))
    op.create_table('entrada_padron',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('email', EncryptedString(length=255), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('comision', sa.String(length=100), nullable=True),
    sa.Column('regional', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['version_padron.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entrada_padron_lookup', 'entrada_padron', ['tenant_id', 'version_id', 'email_hash'], unique=False)
    op.create_index('idx_entrada_padron_usuario', 'entrada_padron', ['tenant_id', 'usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entrada_padron_usuario', table_name='entrada_padron')
    op.drop_index('idx_entrada_padron_lookup', table_name='entrada_padron')
    op.drop_table('entrada_padron')
    op.drop_index('uix_version_padron_active', table_name='version_padron', postgresql_where=sa.text('activa = true AND deleted_at IS NULL'))
    op.drop_index('idx_version_padron_lookup', table_name='version_padron')
    op.drop_table('version_padron')
    # ### end Alembic commands ###
