"""Add FK to audit_log.materia_id

Revision ID: 0e9339c786f7
Revises: e21b72dc6345
Create Date: 2026-06-08 00:30:05.255705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e9339c786f7'
down_revision: Union[str, Sequence[str], None] = 'e21b72dc6345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tareas',
    sa.Column('materia_id', sa.UUID(), nullable=True),
    sa.Column('asignado_a', sa.UUID(), nullable=False),
    sa.Column('asignado_por', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_PROGRESO', 'RESUELTA', 'CANCELADA', name='estadotareaenum'), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('contexto_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_a'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['asignado_por'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentarios_tarea',
    sa.Column('tarea_id', sa.UUID(), nullable=False),
    sa.Column('autor_id', sa.UUID(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'audit_log', 'materias', ['materia_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_log', type_='foreignkey')
    op.drop_table('comentarios_tarea')
    op.drop_table('tareas')
    # ### end Alembic commands ###
