"""create_aviso_tables

Revision ID: 2778125dd6de
Revises: ae0a8aa0be85
Create Date: 2026-06-06 20:05:41.427508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2778125dd6de'
down_revision: Union[str, Sequence[str], None] = 'ae0a8aa0be85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avisos',
    sa.Column('alcance', sa.Enum('GLOBAL', 'POR_MATERIA', 'POR_COHORTE', 'POR_ROL', name='alcanceenum'), nullable=False),
    sa.Column('materia_id', sa.UUID(), nullable=True),
    sa.Column('cohorte_id', sa.UUID(), nullable=True),
    sa.Column('rol_destino', sa.String(), nullable=True),
    sa.Column('severidad', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('cuerpo', sa.Text(), nullable=False),
    sa.Column('inicio_en', sa.DateTime(), nullable=False),
    sa.Column('fin_en', sa.DateTime(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('requiere_ack', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acknowledgment_avisos',
    sa.Column('aviso_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aviso_id'], ['avisos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aviso_id', 'usuario_id', name='uq_aviso_usuario_ack')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acknowledgment_avisos')
    op.drop_table('avisos')
    # ### end Alembic commands ###
