"""crear_tablas_evaluaciones

Revision ID: ae0a8aa0be85
Revises: 2f900dcbe886
Create Date: 2026-06-06 19:37:18.970378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0a8aa0be85'
down_revision: Union[str, Sequence[str], None] = '2f900dcbe886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluaciones',
    sa.Column('materia_id', sa.UUID(), nullable=False),
    sa.Column('cohorte_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('PARCIAL', 'TP', 'COLOQUIO', 'RECUPERATORIO', name='evaluacion_tipo_enum'), nullable=False),
    sa.Column('instancia', sa.String(length=255), nullable=False),
    sa.Column('dias_disponibles', sa.Integer(), nullable=False),
    sa.Column('cupos_totales', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cohorte_id'], ['cohortes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['materia_id'], ['materias.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reservas_evaluacion',
    sa.Column('evaluacion_id', sa.UUID(), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'CANCELADA', name='estado_reserva_enum'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_id', 'alumno_id', name='uq_reserva_alumno_evaluacion')
    )
    op.create_table('resultados_evaluacion',
    sa.Column('evaluacion_id', sa.UUID(), nullable=False),
    sa.Column('alumno_id', sa.UUID(), nullable=False),
    sa.Column('nota_final', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, update_expression=None),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['usuario.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluacion_id', 'alumno_id', name='uq_resultado_alumno_evaluacion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_evaluacion')
    op.drop_table('reservas_evaluacion')
    op.drop_table('evaluaciones')
    # ### end Alembic commands ###
